### ISSUE TITLE
INIT FAILURE

### ISSUE THREAD

**Issue by segisito** [giuliosavian/Webscaper-and-Telegram-bot#1]
Is this normal?  i changed the urls for spain and nothing happends, can u help me?

**Comment by giuliosavian** [comment]
I will give it a look and replay!

By a first look I attach two notes:
- It is necessary to do some debug inside the "web_scraper" function for understand in which line there is the problem.
- one possibility is to update the HTML labels of the Vinted site.

**Comment by segisito** [comment]
I think is trying donwload the image of article 
am-bot-main/Webscaper-and-Telegram-bot-main/import_telebot.py
Recived message:camisa
thread 'main' panicked at 'Downloaded file cannot be uncompressed (xml extension)', src\files.rs:46:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'Downloaded file cannot be uncompressed (xml extension)', src\files.rs:46:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Error

But alwais dop this : 
![image](https://github.com/giuliosavian/Webscaper-and-Telegram-bot/assets/55485789/33e2265b-34a5-4dae-bdff-29b09fff03dc)

**Comment by giuliosavian** [comment]
Hi,

I was not able to replicate your issue.
I need more information, can you add your Error message? and the section regarding the issue?

Note: You have to update the '''attrs''' of the following section according to the vinted site:
```
 #scraping the boxes
        for box in page.findAll('div', attrs={"class" : "new-item-box__container"}):


            #scraping the name the prize and the link for on a single box
            advertisement = []

            #CATEGORY
            tmp = box.find('div', attrs={'new-item-box__description'})
            category = tmp.find('h4', attrs={'web_ui__Text__text web_ui__Text__caption web_ui__Text__left'})
            print(tmp.text)
            print(category.text)
            categories.append(category.text)
            advertisement.append(category.text)
            #print(category.text)
            #print("OK category")

            #PRICE
            price = box.find('div', attrs={'title-content'})
            print(price)
            price_raw = price.text
            price_clean = price_raw.replace('\xa0', '')
            prices.append(price_clean)
            advertisement.append(price_clean)
            #print("OK price")

            #LINK
            tmp = box.find('div', attrs={'class' : 'u-position-relative u-min-height-none u-flex-auto'})
            print(tmp)
            link = tmp.find('a')
            print(link)
            links.append(link.get('href'))
            advertisement.append(link.get('href'))
            #SUBCATEGORY

            #IMMAGE and PRODUCT
            tmp = box.find('div', attrs={'web_ui__Image__image web_ui__Image__cover web_ui__Image__portrait web_ui__Image__scaled web_ui__Image__ratio'})
            image_link  = tmp.find('img')
            products.append(image_link.get('alt'))
            #image = io.imread(image_link.get('src'))
            #images.append(image)
            #print(image.get('alt'))
            #print(image.get('src'))
            #advertisement.append(image_link.get('alt'))
            #advertisement.append(image) #Wrong
            #product_data.append(advertisement) # contanins all the data grupped 
```
